using System.Reflection;
using System.Xml.Linq;
using Smylte.Desktop;
using Xunit;

namespace Smylte.Desktop.Tests;

/// The icons the GTK client carries.
///
/// The same art as the `.ico` files and generated by the same script from the
/// same SVG, so what is asserted here is the packaging and the pixels rather
/// than the design: that every variant exists at every size the client asks
/// for, that each raster is a PNG of the size its name claims, and that the
/// four things that make the mark legible survived the reduce.
///
/// The Windows-only assertions do NOT port and are deliberately absent: there
/// is no ICO directory to parse, no `bWidth` byte to overflow, and no
/// 256-encodes-as-0 quirk. What ports is everything about the image, and it
/// ports because AppIconTests reads bytes rather than asking
/// `System.Drawing.Common`, which throws off Windows.
public sealed class LinuxIconTests
{
    /// What the hicolor theme names. Held here as a literal rather than read
    /// from IconChoices, so a size quietly dropped from the shared list fails
    /// against this one rather than agreeing with itself.
    private static readonly int[] Expected = [16, 24, 32, 48, 64, 128, 256];

    private static readonly byte[] Accent = [0xC7, 0x5A, 0x26];

    public static TheoryData<string> Variants() => new() { "accent", "paper", "ink", "mark" };

    private static byte[] Png(string stem, int size) =>
        AppIconTests.Bytes($"linux.{stem}-{size}.png");

    [Fact]
    public void The_client_and_the_generator_agree_on_which_sizes_exist()
    {
        // Both directions. A size the generator emits and the client never
        // unpacks is dead weight in the binary; a size the client asks for and
        // the generator never wrote is a missing icon at exactly one scale
        // factor, which is the kind of gap nobody sees until a screenshot.
        Assert.Equal(Expected.OrderBy(s => s), IconChoices.FreedesktopSizes.OrderBy(s => s));
    }

    [Theory]
    [MemberData(nameof(Variants))]
    public void Every_size_is_present_exactly_once(string stem)
    {
        var names = Assembly.GetExecutingAssembly().GetManifestResourceNames()
            .Where(n => n.StartsWith($"linux.{stem}-", StringComparison.Ordinal))
            .ToList();

        Assert.Equal(Expected.Length, names.Count);
        foreach (var size in Expected)
            Assert.Single(names, n => n == $"linux.{stem}-{size}.png");
    }

    [Theory]
    [MemberData(nameof(Variants))]
    public void Every_raster_is_a_plain_rgba_png_of_the_size_it_claims(string stem)
    {
        foreach (var size in Expected)
        {
            var bytes = Png(stem, size);

            // Signature, then IHDR — which a PNG must carry first, so its
            // fields are at fixed offsets.
            Assert.Equal<byte>([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A], bytes[..8]);
            Assert.Equal("IHDR", System.Text.Encoding.ASCII.GetString(bytes, 12, 4));

            Assert.Equal(size, BigEndian(bytes, 16));
            Assert.Equal(size, BigEndian(bytes, 20));
            Assert.Equal(8, bytes[24]);      // bit depth
            Assert.Equal(6, bytes[25]);      // colour type 6 = RGBA
            Assert.Equal(0, bytes[28]);      // interlace: none. The decoder
                                             // below reads scanlines in order.
        }
    }

    [Theory]
    [MemberData(nameof(Variants))]
    public void The_accent_period_survives_at_every_size(string stem)
    {
        // The one coloured thing in the mark, and the smallest. Below 24 the
        // generator replaces the disc with a whole-pixel square precisely
        // because a reduced disc washes out — so this is the assertion that
        // says the hinting worked, at the sizes where it had to.
        foreach (var size in Expected)
        {
            var pixels = AppIconTests.Decode(Png(stem, size), size);
            var found = false;
            for (var i = 0; i < pixels.Length && !found; i += 4)
            {
                if (pixels[i + 3] < 250) continue;
                var distance = Math.Sqrt(
                    Math.Pow(pixels[i] - Accent[0], 2) +
                    Math.Pow(pixels[i + 1] - Accent[1], 2) +
                    Math.Pow(pixels[i + 2] - Accent[2], 2));
                found = distance <= 10;
            }
            Assert.True(found, $"{stem}-{size}.png has no opaque pixel within 10 of #C75A26");
        }
    }

    [Theory]
    [MemberData(nameof(Variants))]
    public void Nothing_is_pure_black_or_pure_white(string stem)
    {
        // The design system's inks are #0E0E0C and #F4F1E8, never #000000 or
        // #FFFFFF, and the generator goes out of its way to keep the reduce
        // from producing either — a transparent ground filled with black drags
        // every edge toward it. Alpha >= 250 only: a fringe pixel is allowed to
        // be anything, an opaque one is not.
        foreach (var size in Expected)
        {
            var pixels = AppIconTests.Decode(Png(stem, size), size);
            for (var i = 0; i < pixels.Length; i += 4)
            {
                if (pixels[i + 3] < 250) continue;
                var pure = pixels[i] == pixels[i + 1] && pixels[i + 1] == pixels[i + 2];
                Assert.False(pure && pixels[i] == 0, $"{stem}-{size}.png has a pure black pixel");
                Assert.False(pure && pixels[i] == 255, $"{stem}-{size}.png has a pure white pixel");
            }
        }
    }

    [Fact]
    public void The_bare_mark_is_cut_out_and_the_plated_variants_are_a_tile()
    {
        // The whole difference between `mark` and the other three, and the one
        // an emitter that ignored `plate=None` would silently erase.
        //
        // Stated as COVERAGE, not as "has a transparent pixel". The plated
        // variants have transparent pixels too — the plate's corners are
        // rounded, which is a deliberate departure from the editorial system's
        // `border-radius: 0` and is why the naive test is wrong. Measured, the
        // plates run 95-99% opaque and the bare mark 12-22%, so the thresholds
        // below have most of that gap between them and are not tuned to the
        // current art.
        foreach (var size in Expected)
        {
            Assert.True(Opacity(Png("mark", size), size) < 0.50,
                $"mark-{size}.png is mostly opaque; the bare variant should be cut out");
            foreach (var plated in new[] { "accent", "paper", "ink" })
                Assert.True(Opacity(Png(plated, size), size) > 0.80,
                    $"{plated}-{size}.png is mostly transparent; it should be a plate");
        }
    }

    [Theory]
    [MemberData(nameof(Variants))]
    public void The_scalable_variant_is_the_same_drawing(string stem)
    {
        var svg = XDocument.Parse(
            System.Text.Encoding.UTF8.GetString(AppIconTests.Bytes($"linux.{stem}.svg")));
        var root = svg.Root!;

        Assert.Equal("0 0 256 256", root.Attribute("viewBox")?.Value);

        // One letter, one period, and a plate for everything but the bare mark.
        // Cheap to check and it catches the failure that matters: an emitter
        // that wrote the plate for every variant, or none.
        Assert.Single(root.Elements().Where(e => e.Name.LocalName == "polygon"));
        Assert.Single(root.Elements().Where(e => e.Name.LocalName == "circle"));
        Assert.Equal(stem == "mark" ? 0 : 1,
            root.Elements().Count(e => e.Name.LocalName == "rect"));

        // The accent is somewhere in every variant — as the plate, as the
        // period, or as the mark itself.
        Assert.Contains("#c75a26", svg.ToString(), StringComparison.OrdinalIgnoreCase);
    }

    /// What fraction of the raster is fully opaque.
    private static double Opacity(byte[] png, int size)
    {
        var pixels = AppIconTests.Decode(png, size);
        var opaque = 0;
        for (var i = 3; i < pixels.Length; i += 4)
            if (pixels[i] >= 250) opaque++;
        return opaque / (double)(size * size);
    }

    private static int BigEndian(byte[] bytes, int at) =>
        (bytes[at] << 24) | (bytes[at + 1] << 16) | (bytes[at + 2] << 8) | bytes[at + 3];
}
